### PR TITLE
Upgrade fontawesome to FA 6.2.1 version

### PR DESCRIPTION
**Pull request by rich-iannone**
This updates the icons to the FontAwesome 6.2.1 version (2,018 free icons). This also adds back some v4 compat files that were missing in the last release.

Fixes: https://github.com/rstudio/fontawesome/issues/99
Fixes: https://github.com/rstudio/fontawesome/issues/100

### CODE REVIEW

**Review by cderv — COMMENTED** [review]
Maybe you want to try fix the test before any other review ?

**Comment by rich-iannone** [comment]
Hmmm, yes. I've seen this recently for gt tests (only for Windows, not Ubuntu) were `testthat` wasn't installed. I'll investigate further.

**Comment by rich-iannone** [comment]
@cderv i went to a more standard R CMD checking workflow and everything is okay again.

**Review by cderv — APPROVED** [review]
Not an expert in Fontawesome and the internal of the package, but the update seems good to me. You know the process the best.

**Pull request merged**
